name: learnvironment
description: Have you ever wondered how to engage students in learning about sustainability in a fun and interactive way? 
 Our app offers a unique platform for teachers to help students aged 6-16 learn recycling, citizenship and sustainability through engaging games. 
 Teachers can create classes, assign personalized games, and track student progress with detailed performance stats. 
 Unlike traditional methods, our app offers a dynamic learning experience with age-appropriate games, verified content, and a bibliography for each game that cites the sources of the information, ensuring accuracy and trustworthiness.
 Start making sustainability education more enjoyable and impactful today with our app!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.5
  firebase_ui_auth: ^1.16.1
  path_provider: ^2.0.11
  flutter_local_notifications: ^19.2.1
  shared_preferences: ^2.5.3
  just_audio: ^0.9.36
  audioplayers: ^6.4.0
  http: ^1.4.0
  uuid: any
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.2
  coverage: ^1.13.1
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.4.6
  test: ^1.25.15
  flutter_launcher_icons: ^0.14.3
  mocktail: ^1.0.4
  fake_cloud_firestore: ^3.0.0
  firebase_auth_mocks: ^0.14.0

flutter_icons:
 android: true
 ios: false
 image_path: "assets/Icon.png"

flutter:
  uses-material-design: true
  assets:
  - assets/widget.png
  - assets/right.png
  - assets/wrong.png
  - assets/green_bin.png
  - assets/blue_bin.png
  - assets/brown_bin.png
  - assets/yellow_bin.png
  - assets/red_bin.png
  - assets/trash1.png
  - assets/trash2.png
  - assets/trash3.png
  - assets/trash4.png
  - assets/trash5.png
  - assets/trash6.png
  - assets/trash7.png
  - assets/trash8.png
  - assets/trash9.png
  - assets/trash10.png
  - assets/open_green_bin.png
  - assets/open_yellow_bin.png
  - assets/open_blue_bin.png
  - assets/open_brown_bin.png
  - assets/open_red_bin.png
  - assets/icon.png
  - assets/right.png
  - assets/wrong.png
  - assets/quizLogo.png
  - assets/placeholder.png
  - assets/right.png
  - assets/wrong.png
  - assets/green_bin.png
  - assets/blue_bin.png
  - assets/brown_bin.png
  - assets/yellow_bin.png
  - assets/red_bin.png
  - assets/trash1.png
  - assets/trash2.png
  - assets/trash3.png
  - assets/trash4.png
  - assets/trash5.png
  - assets/trash6.png
  - assets/trash7.png
  - assets/trash8.png
  - assets/trash9.png
  - assets/trash10.png
  - assets/open_green_bin.png
  - assets/open_yellow_bin.png
  - assets/open_blue_bin.png
  - assets/open_brown_bin.png
  - assets/open_red_bin.png
  - assets/correct_answer.mp3
  - assets/wrong_answer.mp3
