// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiU99jLzKcMcFAKSM2MF-x8cMx6vLyNcw',
    appId: '1:333663693928:web:e1a0128c6e340459311fdd',
    messagingSenderId: '333663693928',
    projectId: 'testdatabase-fcb29',
    authDomain: 'testdatabase-fcb29.firebaseapp.com',
    storageBucket: 'testdatabase-fcb29.firebasestorage.app',
    measurementId: 'G-KEXSS5W1TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM9qtQ0VMSfi42Fm2VjbDgVVJB5-Kau5Y',
    appId: '1:333663693928:android:df8ae8dac7bf42b5311fdd',
    messagingSenderId: '333663693928',
    projectId: 'testdatabase-fcb29',
    storageBucket: 'testdatabase-fcb29.firebasestorage.app',
  );
}
